#!/usr/bin/env python3
"""Generate a kconfig fragment that switches off driver families we do not need.

    prune-drivers.sh <base-config> <output-fragment> <allowlist-fragment>...

Reads prune-rules.conf next to this script. For every symbol that is enabled
in the base config and matches a rule's glob, emits `# CONFIG_X is not set`
-- unless the symbol is on that rule's keep-list, or is explicitly enabled by
one of the allowlist fragments passed in.

The output is regenerated on every build rather than committed, so it can
never drift from the base config it was derived from.
"""
import fnmatch
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RULES = os.path.join(HERE, "prune-rules.conf")


def enabled_symbols(path):
    """Symbols set to y or m in a config or fragment."""
    out = set()
    for line in open(path):
        m = re.match(r"CONFIG_([A-Za-z0-9_]+)=(y|m)\s*$", line)
        if m:
            out.add(m.group(1))
    return out


def read_rules(path):
    """Parse the rules file; a trailing backslash continues a keep-list."""
    rules = []
    pending = ""
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.endswith("\\"):
            pending += line[:-1] + " "
            continue
        line, pending = pending + line, ""
        glob, *keep = line.split()
        rules.append((glob, set(keep)))
    return rules


def main(argv):
    if len(argv) < 3:
        sys.exit(__doc__)
    base, out, allowlists = argv[1], argv[2], argv[3:]

    rules = read_rules(RULES)
    candidates = enabled_symbols(base)

    # Never touch anything the hardware allowlist asked for.
    exempt = set()
    for frag in allowlists:
        exempt |= enabled_symbols(frag)
    for _, keep in rules:
        exempt |= keep

    disabled = {}
    for sym in sorted(candidates):
        if sym in exempt:
            continue
        for glob, _ in rules:
            if fnmatch.fnmatchcase(sym, glob):
                disabled[sym] = glob
                break

    with open(out, "w") as fh:
        fh.write("# Generated by prune-drivers.sh -- do not edit.\n")
        fh.write("# Source of truth: kernel/prune-rules.conf\n\n")
        by_rule = {}
        for sym, glob in disabled.items():
            by_rule.setdefault(glob, []).append(sym)
        for glob in [g for g, _ in rules if g in by_rule]:
            fh.write("# %s (%d)\n" % (glob, len(by_rule[glob])))
            for sym in sorted(by_rule[glob]):
                fh.write("# CONFIG_%s is not set\n" % sym)
            fh.write("\n")

    print(":: pruned %d driver symbols across %d rules -> %s"
          % (len(disabled), len(by_rule), out))


if __name__ == "__main__":
    main(sys.argv)
